version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - /myDockerVolume/db:/data/db
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=matcha
      - MONGO_INITDB_ROOT_PASSWORD=matcha
    ports: 
      - "27017:27017"
  matcha:
    container_name: matcha
    # image: alvinmaquena/matcha:0.0.1
    build: .
    environment:
      - MATCHA_MONGODB_USERNAME=matcha
      - MATCHA_MONGODB_PASSWORD=matcha
      - MATCHA_MONGODB_HOST=mongodb
      - MATCHA_MONGODB_DATABASE=matcha
      - MATCHA_MONGODB_IP=mongodb
      - MATCHA_MONGODB_PORT=27017
      - PORT=5000
    ports:
      - "5000:5000"
      - "8080:8080"
    depends_on:
      - mongodb